services:
  - type: web
    name: upscaler
    env: python
    buildCommand: |
      pip install torch==2.0.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      pip install -r requirements.txt
      npm install
    startCommand: node server/index.js
